# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a21e6e4f38427338803403e0f3ebc76d64dc394144562d9540307db40413c2e0ad2d3577561454072d6a1d743600a4bcdaeef9ffee881e2c7330b38ab2ed092f

test:
  secret_key_base: 8e6681b199587d0fcfd663369c45a65b425fd721d110132ffe2776344a83622f7005bf8262d5497714a6852bad37e520c15600b467b26fa0dfb2177d51719865

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
